---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-repo
  namespace: longhorn-system # Required for Renovate lookups
spec:
  interval: 30m
  url: https://charts.longhorn.io
  timeout: 2m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
  values:
    persistence:
      defaultClass: false
    defaultSettings:
      #backupTarget: "nfs://${NFS_SERVER}:/dumpster/backups/apps/longhorn"
      defaultDataPath: /var/lib/longhorn_data
      defaultReplicaCount: 2
      storageMinimalAvailablePercentage: 10
    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: "nginx"
    #     # https://goauthentik.io/docs/providers/proxy/forward_auth
    #     nginx.ingress.kubernetes.io/auth-url: |-
    #         http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
    #     # If you're using domain-level auth, use the authentication URL instead of the application URL
    #     nginx.ingress.kubernetes.io/auth-signin: |-
    #         https://longhorn.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
    #     nginx.ingress.kubernetes.io/auth-response-headers: |-
    #         Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    #     nginx.ingress.kubernetes.io/auth-snippet: |
    #         proxy_set_header X-Forwarded-Host $http_host;
    #     hajimari.io/appName: "Longhorn"
    #     hajimari.io/icon: "simple-icons:rancher"
      host: "longhorn.${SECRET_DOMAIN}"
