# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:HeGheXmnzbGgKAGSQOeZUw6W2zZyfbu/t2ugtkW9Mj4r/f/phKFC8WhFgqOvN3Tmj3r0rKI2SY1gazE9iwX+kw7bW7vIq2y2i57vUqBJVqOnjpHqOJG6wBMBKeXtcjtorM+DvzO7xR6SuqTNf20ODxh+ERCa/CwLQ2r5ZFLtEd4xqF0Fx7/g9m8oR5z9VfknDMDSWCg8cJju+BR+idAvK4BojYADCcARf8HtSV2qOHyr7LCV,iv:Zpkppwm1YolwsdA+LLaMvlURZ3jxtB7/aVGEF8uoMaU=,tag:HbbWohFGRsFW5tzW6ycipw==,type:str]
sops:
  age:
    - recipient: age1f3kuy8xcgpdh0lyphkjgx2tazh9lr60m3kyqdr48nlj85ukz7gqqz5rdnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYnN2a2l5bzdCS0JLem44
        U3RtNEVucVJqZTE1dlBBdXV5NzR3aldIdDFZCkR6WldFRGpqZExiOXFzUlZUOWdy
        ZmprQkJkbXRNSlFocmY0U1ZWM3ZqN0kKLS0tIFo5ZFhReC92bWJQTEtORGZyZ3Fo
        S04wQ1FyeG5DREZRNVlwbFFlT2d5UUEKnZ4RsD8nJs1nVJuEOzjTInHT8lRp2cp1
        T2FsKKHRUCFgExmvNIwFvbAaO6/J753fx8Ux41DMYf/2pjDBgss6vQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-26T01:46:05Z"
  mac: ENC[AES256_GCM,data:y5ldDRxqsEL+RAuCWXQuT83Oy0yZrLfT4bI1Duq5gW1CT32+kLQqwOEwgIIhXXQg2g7TTM+J2ECcyAbijfMfAPQd/NfGNzwoVYbgJcDrRAt+/9Ii3i6LQ95PyWxPKE3atF12GjlcdzhkoRW25uNKLPOlp8eWKKnbjEvwfQreLCk=,iv:YZNtewdrNFrQrJW7mo61Z+ZEpd6SCKhhzxpFRxhinyM=,tag:PK2TlN3wEAqQeq6GHG9xiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
