---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  path: ./kubernetes/apps/longhorn-system/longhorn/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-longhorn-ingress-authentik
#   namespace: flux-system
# spec:
#   path: ./kubernetes/apps/longhorn-system/longhorn/ingress-authentik
#   dependsOn:
#     - name: cluster-apps-ingress-nginx
#     - name: cluster-apps-authentik
#     - name: cluster-apps-longhorn
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
