apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:AuGVUA5Bi6yM5iApNUM=,iv:FyMhuKdjyG5RyO4HnKwCyWx2p91DCp75U9JGigJ43/8=,tag:9VVcu43XMfz3FxPrFYYq8g==,type:str]
sops:
  age:
    - recipient: age1f3kuy8xcgpdh0lyphkjgx2tazh9lr60m3kyqdr48nlj85ukz7gqqz5rdnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTUFpa0lNcWtBcEROaWtW
        REFZQjloYUEwZHhMZEpjVTFzU04rNXBtTm1NCi9qZzV5YUFZWjlJRThwc0xzUjlC
        cTludXppSzdiRXR2emxZTXlHL2FTYW8KLS0tIFFhcTYwN1lhWitxQUZnTlVWeUN4
        bEc0MUhOSGNERWxWdmREVWlPVXFaZTQKmO0Sis5DqnqL3NJRmXRicD4fD2dwDwjp
        RDHuBWl5sPZPu3es62mZsFrGBT0FBs2HMrRJL3TNHgqKn+0vw6CKmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-29T20:53:52Z"
  mac: ENC[AES256_GCM,data:fv2OtMsTyuHWhFCocwaITzyZiEaTMu6rOGjn4eUcm4a4yoT2V95kW9gffUPWIOxR6m29Ef9fSvC0gnYCQ/bCR0JcNmW2K2SMKiRrmZDK3xR012A4/G4tB0jqwHZAXUcvwj+EyRTHu8oZjl8a7thvgU5uIu6icCX0C1Ygh/TlFkE=,iv:d5SRl33/k1QsbpCKryrPtGBNReNojQDevpNYILm8YS4=,tag:mcQU2m2tUZt9gZbiKa6iiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
